import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Calendar as CalendarIcon, FileText, User, Settings, Layers, Search, Plus, Send, Camera, Share2, Globe, Radio, SlidersHorizontal, ChevronDown, Trash2 } from 'lucide-react';
export const Sidebar = ({ currentTab, onSelectTab, workspaces, activeWorkspaceId, onSelectWorkspace, onDeleteWorkspace, channels, selectedChannelId, onSelectChannel, onOpenSearch, user, onAddWorkspace, conflictCount, }) => {
    const currentWorkspace = workspaces.find((w) => w.id === activeWorkspaceId) || workspaces[0] || { id: '', name: 'Default', role: 'Владелец', membersCount: 1 };
    const userName = user?.name || 'Пользователь';
    const initials = userName.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'П';
    const roleLabel = user?.role === 'admin' ? 'Администратор' : user?.role === 'editor' ? 'Редактор' : 'Пользователь';
    const getPlatformIcon = (platform) => {
        switch (platform) {
            case 'telegram':
                return _jsx(Send, { className: "w-3.5 h-3.5 text-sky-400" });
            case 'vk':
                return _jsx(Share2, { className: "w-3.5 h-3.5 text-blue-400" });
            case 'instagram':
                return _jsx(Camera, { className: "w-3.5 h-3.5 text-pink-400" });
            case 'youtube':
                return _jsx(Radio, { className: "w-3.5 h-3.5 text-red-400" });
            case 'website':
                return _jsx(Globe, { className: "w-3.5 h-3.5 text-emerald-400" });
            default:
                return _jsx(Layers, { className: "w-3.5 h-3.5 text-gray-400" });
        }
    };
    return (_jsxs("aside", { className: "w-64 bg-[#19171b] border-r border-[#2b2732] flex flex-col h-screen select-none shrink-0 text-sm", children: [_jsx("div", { className: "p-4 border-b border-[#2b2732] flex items-center justify-between", children: _jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("div", { className: "w-8 h-8 rounded-lg bg-gradient-to-tr from-[#e5484d] to-[#ff6b6b] flex items-center justify-center shadow-md shadow-red-500/20", children: _jsxs("div", { className: "relative w-4 h-4 flex flex-col justify-between py-0.5", children: [_jsx("span", { className: "block h-0.5 w-full bg-white rounded-full" }), _jsx("span", { className: "block h-0.5 w-full bg-white/90 rounded-full" }), _jsx("span", { className: "block h-0.5 w-full bg-white/80 rounded-full" })] }) }), _jsx("span", { className: "font-semibold text-lg tracking-tight text-white", children: "\u041A\u043E\u043D\u0442\u0435\u043D\u0442\u043D\u043E" })] }) }), _jsx("div", { className: "px-3 pt-3", children: _jsxs("button", { onClick: onOpenSearch, className: "w-full flex items-center justify-between px-3 py-2 rounded-lg bg-[#221f26] hover:bg-[#2a2630] border border-[#322d3a] text-gray-400 hover:text-gray-200 transition-colors text-xs", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Search, { className: "w-3.5 h-3.5 text-gray-400" }), _jsx("span", { children: "\u041F\u043E\u0438\u0441\u043A" })] }), _jsx("kbd", { className: "px-1.5 py-0.5 text-[10px] bg-[#1a171d] rounded border border-[#3b3446] text-gray-400 font-mono", children: "\u2318 K" })] }) }), _jsxs("div", { className: "px-3 py-3 space-y-1", children: [_jsxs("button", { onClick: () => onSelectTab('calendar'), className: `w-full flex items-center justify-between px-3 py-2 rounded-lg text-xs font-medium transition-all ${currentTab === 'calendar'
                            ? 'bg-[#2b2432] text-white border border-[#483754]'
                            : 'text-gray-300 hover:bg-[#231f28] hover:text-white'}`, children: [_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx(CalendarIcon, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { children: "\u041A\u0430\u043B\u0435\u043D\u0434\u0430\u0440\u044C" })] }), conflictCount > 0 && (_jsx("span", { className: "px-1.5 py-0.2 text-[10px] font-semibold bg-red-500/20 text-red-400 border border-red-500/40 rounded", children: conflictCount }))] }), _jsxs("button", { onClick: () => onSelectTab('materials'), className: `w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-medium transition-all ${currentTab === 'materials'
                            ? 'bg-[#2b2432] text-white border border-[#483754]'
                            : 'text-gray-300 hover:bg-[#231f28] hover:text-white'}`, children: [_jsx(FileText, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { children: "\u041C\u0430\u0442\u0435\u0440\u0438\u0430\u043B\u044B" })] }), _jsxs("button", { onClick: () => onSelectTab('media'), className: `w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-medium transition-all ${currentTab === 'media'
                            ? 'bg-[#2b2432] text-white border border-[#483754]'
                            : 'text-gray-300 hover:bg-[#231f28] hover:text-white'}`, children: [_jsx(Camera, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { children: "\u041C\u0435\u0434\u0438\u0430" })] }), _jsxs("button", { onClick: () => onSelectTab('profile'), className: `w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-xs font-medium transition-all ${currentTab === 'profile'
                            ? 'bg-[#2b2432] text-white border border-[#483754]'
                            : 'text-gray-300 hover:bg-[#231f28] hover:text-white'}`, children: [_jsx(User, { className: "w-4 h-4 text-gray-400" }), _jsx("span", { children: "\u041F\u0440\u043E\u0444\u0438\u043B\u044C" })] })] }), _jsx("div", { className: "h-px bg-[#26222b] mx-3 my-1" }), _jsxs("div", { className: "px-3 py-2 flex-1 overflow-y-auto", children: [_jsx("div", { className: "flex items-center justify-between px-2 mb-1.5", children: _jsx("span", { className: "text-[10px] font-semibold uppercase tracking-wider text-gray-400", children: "\u041F\u0420\u041E\u0421\u0422\u0420\u0410\u041D\u0421\u0422\u0412\u0410" }) }), _jsxs("div", { className: "space-y-0.5", children: [workspaces.map((ws) => (_jsxs("div", { className: `group flex items-center gap-1 rounded-md transition-colors ${activeWorkspaceId === ws.id ? 'bg-[#2c2635]' : 'hover:bg-[#221e27]'}`, children: [_jsxs("button", { onClick: () => onSelectWorkspace(ws.id), "aria-current": activeWorkspaceId === ws.id ? 'page' : undefined, className: `min-w-0 flex-1 flex items-center justify-between px-2.5 py-1.5 rounded-md text-xs transition-colors ${activeWorkspaceId === ws.id
                                            ? 'text-white font-medium'
                                            : 'text-gray-300 hover:text-gray-100'}`, children: [_jsxs("div", { className: "flex items-center gap-2 truncate", children: [_jsx(Layers, { className: "w-3.5 h-3.5 text-gray-400 shrink-0" }), _jsx("span", { className: "truncate", children: ws.name })] }), _jsx("span", { className: "text-[10px] text-gray-400", children: ws.role })] }), _jsx("button", { onClick: () => onDeleteWorkspace(ws.id), disabled: workspaces.length <= 1, title: workspaces.length <= 1 ? 'Нельзя удалить последнее пространство' : `Удалить пространство «${ws.name}»`, "aria-label": `Удалить пространство «${ws.name}»`, className: "mr-1 p-1 rounded text-gray-500 opacity-0 group-hover:opacity-100 hover:text-red-300 hover:bg-red-950/40 disabled:cursor-not-allowed disabled:opacity-25 transition-all", children: _jsx(Trash2, { className: "w-3 h-3" }) })] }, ws.id))), _jsxs("button", { onClick: onAddWorkspace, className: "w-full flex items-center gap-2 px-2.5 py-1.5 rounded-md text-xs text-rose-400/80 hover:text-rose-300 hover:bg-[#252029] transition-colors", children: [_jsx(Plus, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "+ \u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043F\u0440\u043E\u0441\u0442\u0440\u0430\u043D\u0441\u0442\u0432\u043E" })] })] }), _jsxs("div", { className: "mt-5", children: [_jsx("div", { className: "flex items-center justify-between px-2 mb-1.5", children: _jsxs("span", { className: "text-[10px] font-semibold uppercase tracking-wider text-gray-400", children: ["\u041A\u0410\u041D\u0410\u041B\u042B \u00B7 ", currentWorkspace.name.toUpperCase()] }) }), _jsxs("div", { className: "space-y-0.5", children: [_jsxs("button", { onClick: () => onSelectChannel(null), className: `w-full flex items-center gap-2 px-2.5 py-1.5 rounded-md text-xs transition-colors ${selectedChannelId === null
                                            ? 'bg-[#24202b] text-white font-medium'
                                            : 'text-gray-400 hover:bg-[#201d25] hover:text-gray-200'}`, children: [_jsx(SlidersHorizontal, { className: "w-3.5 h-3.5 text-gray-400" }), _jsx("span", { children: "\u0412\u0441\u0435 \u043A\u0430\u043D\u0430\u043B\u044B" })] }), channels.map((ch) => (_jsx("button", { onClick: () => onSelectChannel(selectedChannelId === ch.id ? null : ch.id), className: `w-full flex items-center justify-between px-2.5 py-1.5 rounded-md text-xs transition-colors ${selectedChannelId === ch.id
                                            ? 'bg-[#2b2533] text-white font-medium border-l-2 border-[#f25a5a]'
                                            : 'text-gray-400 hover:bg-[#201d25] hover:text-gray-200'}`, children: _jsxs("div", { className: "flex items-center gap-2 truncate", children: [getPlatformIcon(ch.platform), _jsx("span", { className: "truncate", children: ch.name })] }) }, ch.id)))] })] })] }), _jsxs("div", { className: "p-3 border-t border-[#27232e] bg-[#161418] space-y-2", children: [_jsxs("button", { onClick: () => onSelectTab('settings'), className: `w-full flex items-center gap-2.5 px-3 py-1.5 rounded-md text-xs transition-colors ${currentTab === 'settings'
                            ? 'bg-[#282330] text-white'
                            : 'text-gray-400 hover:text-gray-200 hover:bg-[#201d25]'}`, children: [_jsx(Settings, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438" })] }), _jsxs("div", { onClick: () => onSelectTab('profile'), className: "flex items-center justify-between p-2 rounded-lg bg-[#201d26] hover:bg-[#27232f] cursor-pointer transition-colors border border-[#2c2834]", children: [_jsxs("div", { className: "flex items-center gap-2.5 min-w-0", children: [_jsx("div", { className: "w-7 h-7 rounded-full bg-[#3d374a] text-purple-200 flex items-center justify-center font-medium text-xs", children: initials }), _jsxs("div", { className: "truncate", children: [_jsx("div", { className: "text-xs font-medium text-gray-200 truncate", children: userName }), _jsx("div", { className: "text-[10px] text-gray-400 truncate", children: roleLabel })] })] }), _jsx(ChevronDown, { className: "w-3.5 h-3.5 text-gray-400" })] })] })] }));
};
